version: '3.8'

services:
  web:
    build:
      context: ./app
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=postgres
      - DATABASE_USER=yourUser
      - DATABASE_PASSWORD=postgres_PW
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=yourUser
      - POSTGRES_PASSWORD=postgres_PW
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    restart: always
    networks:
      - backend

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=muellol7@students.zhaw.ch
      - PGADMIN_DEFAULT_PASSWORD=postgres_PW
    ports:
      - '5050:80'
    restart: always
    networks:
      - backend  

networks:
  backend:
